#
###################################
# Site wide configuration
####################################
#
title:       "举个桃子的个人小站"
description: "WuDi's Blog. A front-end web developer. Working for ArchForce in Shenzhen, China."
keywords: "吴迪、举个桃子、举个桃子的小站、jugetaozi、wudi、Wudi's Blog、Front-End Engineer、举个桃子的个人小站"
url: https://jugetaozi.github.io # the base hostname & protocol for your site
###################################
# Jekyll configuration
####################################
# 
markdown:          kramdown
excerpt_separator: <!--more-->
permalink:         /:title/
paginate:          10
paginate_path:     "blog/:num"
plugins:              [jekyll-paginate]
port: 4001

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Sass
####################################
#
sass:
  style: compressed

#
###################################
# loading
####################################
#
loading: "https://www.jugetaozi.github.io/img/loading.gif"

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 举个桃子
  avatar: avatar.jpg
  job: "front-end developer"
  bio: "一生想做优雅前端"
  email: 156343782@qq.com
  disqus-shortname: #username
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: #UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jugetaozi #username
  stackoverflow: #123456/username   from a "https://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: jugetaozi
  youtube: #username
  soundcloud: #username
  weibo: myanswer123 #username
  flickr: #username
  codepen: #username
  zhihu: #se7en-zone username